AWS_ACCESS_KEY_ID: "AKIAJQHR7BN3VYFV57MQ"
AWS_SECRET_ACCESS_KEY: "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"
FOG_DIRECTORY: "igram-rails"


GOOGLE_ACCESS_KEY_ID: "GOOGWWS2TBKOEU7TEOUD57ZJ"
GOOGLE_SECRET_ACCESS_KEY: "yxECordPGE5OsySLphiscDoPrOGGXG7jfI0JCKr2"
FOG_DIRECTORY: "igram"


